version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/backend/node_modules
    networks:
      - yolo-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - client-data:/client/node_modules
    networks:
      - yolo-network

networks:
  yolo-network:

volumes:
  backend-data:
  client-data:
