- hosts: all
  become: yes
  vars:
    app_name: "{{ app_name }}"
    frontend_port: "80"
    backend_port: "3000"
  tasks:
    - name: Install Docker
      become: yes
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
        become: yes
        apt:
          name: docker-compose
          state: present

    - name: Clone repository
      become: yes
      git:
        repo: https://github.com/DevSheila/yolo.git
        dest: "/opt/{{ app_name }}"

    - name: Build and run frontend container # Builds and runs the frontend container
      become: yes
      docker_container:
        name: frontend
        image: devsheila/yolo-frontend:latest
        state: started
        ports:
          - "{{ frontend_port }}:80"
        volumes:
          - "/opt/{{ app_name }}/frontend:/app"

     -name: Build and run backend container # Builds and runs the backend container
      become: yes
      docker_container:
        name: backend
        image: devsheila/yolo-backend:latest
        state: started
        ports:
          - "{{ backend_port }}:3000"
        volumes:
          - "/opt/{{ app_name }}/backend:/app"