- hosts: all
  become: yes
  vars:
    app_name: "{{ app_name }}"
    frontend_port: "80"
    backend_port: "3000"
  tasks:
    - name: Install Docker
      become: yes
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
        become: yes
        apt:
          name: docker-compose
          state: present

    - name: Clone repository
      become: yes
      git:
        repo: https://github.com/DevSheila/yolo.git
        dest: "/opt/{{ app_name }}"