apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: sheilaasharon/yolo-backend:1.0
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/yolo"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - name: server
    port: 8080
    targetPort: 8080